name: retrogate_server
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  path: ^1.9.0

  dotenv: ^4.2.0
  grpc: ^4.0.4
  protobuf: ^4.0.0
  fpdart: ^1.1.1
  get_it: ^9.1.1
  http: ^1.6.0

dev_dependencies:
  mockito: ^5.0.0
  lints: ^6.0.0
  test: ^1.25.6
